TaskletFusion
spcl/dace pull request #1039
Opened 2022-07-01 09:25 UTC by phschaad

Adapted from https://github.com/spcl/daceml, originally by @orausch.

Fuses two Tasklets when they're only separated by one Memlet or one AccessNode, and the first Tasklet is used nowhere else.

Future improvements / current limitations:
- The transformation is a bit strict and could be applied in more settings. The example below illustrates one such setting. Tasklet `a` could semantically be fused into the remaining Tasklets, but because it has multiple outputs (and consequently multiple assignments), the transformation does not apply.

Example from the provided test case:
![image](https://user-images.githubusercontent.com/9193712/176866622-f4a4f53a-d80a-48aa-a45f-054f9b32edf3.png)
![image](https://user-images.githubusercontent.com/9193712/176866663-f31272ed-a7c7-47b2-b617-69c0a84746e5.png)

Co-authored-by: @orausch

2022-07-01 11:50 UTC, tbennun requested changes
Not there yet. Core functionality now missing

2022-07-01 11:50 UTC, tbennun commented on dace/transformation/helpers.py
> +def find_name_not_in_set(name_set: Set[str], target: Optional[str]) -> str:
this exists in dace.data.find_new_name

2022-07-01 11:50 UTC, tbennun commented on tests/transformations/tasklet_fusion_test.py
> -    language = dtypes.Language.Python if l == 'Python' else dtypes.Language.CPP
this was quite important for c2dace. What happened?

2022-07-01 11:50 UTC, tbennun commented on tests/transformations/tasklet_fusion_test.py
> +    sdfg.save('_dacegraphs/orig_' + ('d' if with_data else 'nd') + '.sdfg')
why?

2022-07-01 11:50 UTC, tbennun commented on tests/transformations/tasklet_fusion_test.py
> +    sdfg.save('_dacegraphs/xformed_' + ('d' if with_data else 'nd') + '.sdfg')
same

2022-07-01 11:50 UTC, tbennun commented on tests/transformations/tasklet_fusion_test.py
> +    map_with_tasklets.to_sdfg().save('_dacegraphs/tmp.sdfg')
same

2022-07-01 11:50 UTC, tbennun commented on tests/transformations/tasklet_fusion_test.py
> -    language = dtypes.Language.Python if l == 'Python' else dtypes.Language.CPP
I'd just add another test

2022-07-01 11:50 UTC, tbennun commented on dace/transformation/dataflow/tasklet_fusion.py
> +        if t1.language is not Language.Python or t2.language is not Language.Python:
please do not use `is` operators for enums (only ==/!=)

2022-07-01 11:50 UTC, tbennun commented on dace/transformation/dataflow/tasklet_fusion.py
> +        # Both Tasklets must be in Python
That's a bit sad. It was used in c2dace

2022-07-04 11:41 UTC, tbennun approved these changes
LGTM if tests pass

2022-07-04 11:51 UTC, orausch reviewed
LGTM in general, but it would be nice to add the tests from DaCeML, most of them do not require other DaCeML features

2022-07-04 18:16 UTC, merged