OTFMapFusion re-implemented
spcl/dace pull request #1077
Opened 2022-08-03 07:02 UTC by lukastruemper

2022-08-03 07:50 UTC, phschaad requested changes
LGTM overall, minor comments

2022-08-03 07:50 UTC, phschaad commented on dace/transformation/dataflow/otf_map_fusion.py
> +        # Make sure that parameters of first_map_entry
yapf

2022-08-03 07:50 UTC, phschaad commented on dace/transformation/dataflow/otf_map_fusion.py
> +    def solve(first_params, write_accesses, second_params, read_accesses):
This method could use a doc comment maybe

2022-08-03 08:00 UTC, lukastruemper commented on dace/transformation/dataflow/otf_map_fusion.py
> +        # Make sure that parameters of first_map_entry
No yapf for me, version mismatch?

2022-08-05 08:52 UTC, tbennun requested changes
Looks ok in general but there are some misuses of dace symbolics. We cannot use sympy directly as-is. See comments.

2022-08-05 08:52 UTC, tbennun commented on dace/transformation/dataflow/otf_map_fusion.py
> +            - Infer: k -> i - 1, l - > j
improper format, sphinx will complain. Instead, put the expressions in double-backticks:
```
``A[i + 1, j]``
```

2022-08-05 08:52 UTC, tbennun commented on dace/transformation/dataflow/otf_map_fusion.py
> +        """ Infers the memory access for the write memlet given the
missing newline before docstring starts

2022-08-05 08:52 UTC, tbennun commented on dace/transformation/dataflow/otf_map_fusion.py
> +            s = sympy.symbols(f'f_{i}')
symbolic.symbol(...)

2022-08-06 11:59 UTC, tbennun approved these changes
OK from me, but the random connector thing seems odd, especially since we have an API for this (`next_connector`): https://github.com/spcl/dace/blob/master/dace/sdfg/nodes.py#L177

2022-08-06 12:02 UTC, phschaad approved these changes
LGTM in general, only one thing:
For renaming the connectors I would use this: https://github.com/spcl/dace/blob/4645a6a34ababb48d0786eca9f26604e2f8073f1/dace/data.py#L128

2022-08-06 12:05 UTC, lukastruemper commented
> OK from me, but the random connector thing seems odd, especially since we have an API for this (`next_connector`): https://github.com/spcl/dace/blob/master/dace/sdfg/nodes.py#L177

Ah, this is good! I will fix and push later

2022-08-07 14:53 UTC, merged