Frontend: add syntactic sugar for schedule and storage types.
spcl/dace pull request #1088
Opened 2022-08-15 15:48 UTC by orausch

This enables parsing statements like
```python
for i in dace.map[0:N] @ ScheduleType.GPU_Device
  ...
```
And:
```python
def add(X: dace.float32[32] @ StorageType.GPU_Global):
  ...
```

2022-08-15 22:29 UTC, tbennun requested changes
Cool PR!

2022-08-15 22:29 UTC, tbennun commented on dace/data.py
> +            @dace
```suggestion

            @dace
```

2022-08-15 22:29 UTC, tbennun commented on dace/data.py
> +        This lets us write code like:
```suggestion
        This enables controlling the storage location as follows:
```

2022-08-15 22:29 UTC, tbennun commented on tests/python_frontend/device_annotations_test.py
> +import dace
```suggestion
# Copyright 2019-2022 ETH Zurich and the DaCe authors. All rights reserved.
import dace
```

2022-08-16 07:55 UTC, orausch commented
You're going to have to approve for auto-merge :)

2022-08-16 08:03 UTC, gronerl commented
I think this breaks running non-decorated numpy code for the maps, right? Would it make sense to also add a `__matmul__` to `dace.map[]` ?

2022-08-16 08:31 UTC, tbennun approved these changes

2022-08-16 08:31 UTC, tbennun commented
> I think this breaks running non-decorated numpy code for the maps, right? Would it make sense to also add a `__matmul__` to `dace.map[]` ?

Thank you! Done.

2022-08-16 22:10 UTC, merged