Check fpga vendor is supported
spcl/dace pull request #1143
Opened 2022-11-07 15:56 UTC by TizianoDeMatteis

Addresses #1140

2022-11-07 16:24 UTC, tbennun approved these changes

2022-11-08 09:11 UTC, TizianoDeMatteis commented
@tbennun implemented following your suggestion

2022-11-08 14:01 UTC, tbennun requested changes

2022-11-08 14:01 UTC, tbennun commented on dace/codegen/targets/fpga.py
> +
why do you still need this?

2022-11-08 14:35 UTC, TizianoDeMatteis commented on dace/codegen/targets/fpga.py
> +
Good catch! This is just a leftover

2022-11-08 14:42 UTC, tbennun approved these changes

2022-11-08 22:37 UTC, merged