BatchedMatMul: MKL gemm_batch support
spcl/dace pull request #1181
Opened 2022-12-17 14:37 UTC by lukastruemper

2022-12-18 07:19 UTC, tbennun requested changes

2022-12-18 07:19 UTC, tbennun commented on dace/libraries/blas/nodes/batched_matmul.py
> +        const {dtype}** A = new const {dtype}*[{BATCH}];
why malloc in the middle of a potentially performance-critical code??

2022-12-18 07:19 UTC, tbennun commented on dace/libraries/blas/nodes/batched_matmul.py
> +        const {dtype}** A = new const {dtype}*[{BATCH}];
btw that's the reason why we didn't implement it thus far.

2022-12-18 07:20 UTC, tbennun commented
you can try adding the allocation to the init code (if it depends on input symbols or is constant) or the stack (if the batch size is known and small)

2023-02-07 08:38 UTC, lukastruemper commented
> you can try adding the allocation to the init code (if it depends on input symbols or is constant) or the stack (if the batch size is known and small)

I don't know how to move this part to the init part. For BERT with batch size 6-8, the old implementation is much slower than this version

2023-03-16 16:29 UTC, tbennun commented
I'll approve for now, but this should probably use some inflatable workspace.

2023-03-16 18:13 UTC, merged