AugAssignToWCR: Support for more cases and increased test coverage
spcl/dace pull request #1359
Opened 2023-09-01 15:01 UTC by lukastruemper

2023-09-01 15:42 UTC, tbennun requested changes
Thanks! This will improve the transformation greatly. I’d reuse existing helper functions for the nesting. One of the conditions removed is not clearly handled to me.

2023-09-01 15:42 UTC, tbennun commented on dace/transformation/dataflow/wcr_conversion.py
> -            if graph.in_degree(inarr) > 0:
This will be problematic and may create race conditions if state fission is not performed

2023-09-01 15:42 UTC, tbennun commented on tests/transformations/wcr_conversion_test.py
> +    applied = sdfg.apply_transformations_repeated(AugAssignToWCR)
Nice tests. I’d recommend adding something with two inputs like min(a, b) rather than just scalars.

2023-10-27 13:28 UTC, BenWeber42 commented
What's the status of this PR?

2023-11-01 11:12 UTC, BenWeber42 commented
Test failure seems to be affected by #1421. I initiated a re-run of the tests.

2023-11-02 20:26 UTC, tbennun approved these changes

2023-11-03 08:07 UTC, merged