Nice errors and tasklet arguments for the Python frontend
spcl/dace pull request #1365
Opened 2023-09-05 22:21 UTC by tbennun

2023-09-06 08:02 UTC, alexnick83 requested changes
The main changes introduced by this PR (capability for side-effect explicit dataflow tasklets and changes in how an explicit dataflow tasklet's language is interpreted/parsed) need examples/tests. I would like to see a few because I have difficulty understanding the features this PR adds.

2023-09-21 15:50 UTC, tbennun commented on dace/frontend/python/interface.py
> +        self.side_effects = side_effects
Any `dace.tasklet` with a printout and without an output will be removed by dead dataflow elimination. It is strange to add an output dependency there manually. That is the use case here (external function calls).

2023-09-21 15:51 UTC, tbennun commented on dace/frontend/python/memlet_parser.py
> +    try:
It contains no information at all (just IndexError) and no line provenance, so the dace-specific syntax error will even give you the line of code it occurred in.

2023-09-21 15:52 UTC, tbennun commented
@alexnick83 what should we do with this PR? I answered the comments now.

2023-09-25 11:55 UTC, alexnick83 approved these changes

2023-09-25 13:55 UTC, merged