Add offset normalization to Fortran frontend
spcl/dace pull request #1367
Opened 2023-09-08 18:13 UTC by mcopik

This PR contributes a Fortran AST pass to normalize all array offsets. In addition, it fixes a few additional problems:
* Adds a pass to assign parent scope to each AST node.
* Adds a pass accumulating all variable declarations in a given scope.
* Fixes handling of Fortran array assignment when offsets are present.

@acalotoiu I'm going to do a few more tests covering more complex function invocations and 3D arrays. Please look when you can to verify this is the intended behavior.

2023-09-08 19:39 UTC, acalotoiu commented on dace/frontend/fortran/ast_transforms.py
I think there can be other parents: modules.

2023-09-08 19:43 UTC, acalotoiu requested changes
The parent of a node can also be a module no just a function, subroutine or program. The full complexity of Fortan in general is even broader, but modules we require support for directly.

2023-09-08 21:05 UTC, mcopik commented
> The parent of a node can also be a module no just a function, subroutine or program. The full complexity of Fortan in general is even broader, but modules we require support for directly.

@acalotoiu Fixed in commit `70c33dd913376cd87b46887da51da2b5d939f10f`, I also added a test verifying we catch the module as a parent node.

2023-09-11 18:41 UTC, acalotoiu approved these changes
LGTM now. Thanks!

2023-09-11 18:41 UTC, merged