Implement Subsetlist and covers_precise
spcl/dace pull request #1412
Opened 2023-10-30 21:16 UTC by matteonu

This PR adds new functionality to the `Subset` class

- `Subsetlist` is a new Subset that acts as a wrapper of existing subset types. It is essentially a list of Subset objects. The union of two Subsetlists is just the list concatenation.
- `covers_precise()` implements a set cover operation on Subsets of type Range and Indices. If it returns true the first input subset definitely covers the second input subset. Therefore it also takes steps into account.

2023-10-30 22:37 UTC, tbennun commented
Thank you for the contribution. Before reviewing the PR, I have a minor naming comment: perhaps UnionSubset is a better name?

2023-10-31 11:49 UTC, matteonu commented
> Thank you for the contribution. Before reviewing the PR, I have a minor naming comment: perhaps UnionSubset is a better name?

I renamed it `SubsetUnion` now instead of `UnionSubset` (I switched the two words in my head somehow). I hope this works too. If not, I can change it again of course.

2023-10-31 14:12 UTC, matteonu commented
Seems like `subset_intersects_test.py` fails in the build pipeline but I cannot reproduce it locally for some reason.

2023-10-31 17:07 UTC, tbennun commented
It looks like DaCe is still installing SymPy 1.9, and that might be the reason: https://github.com/spcl/dace/actions/runs/6706005794/job/18223680540?pr=1412#step:4:521

 Maybe try changing setup.py to reflect that (`sympy >= 1.9`)

2023-11-01 19:17 UTC, acalotoiu requested changes
Thank you for the contribution! Please make it clear what all the tests are testing.

2023-11-01 22:02 UTC, matteonu commented
I think it is not possible to run the tests on python3.7 with sympy 1.12. According to the official sympy [website](https://docs.sympy.org/latest/install.html) version 1.12 only supports python3.8 and above. I am not sure what else could cause the failing test. I tried to reproduce it by running the commands of the failing test from the `[.github/workflows/general-ci.yml](https://github.com/spcl/dace/blob/3c10cb126ee68b2558f636a73aedf71f4863a125/.github/workflows/general-ci.yml)` locally but I pass the failing test.

2023-11-01 22:20 UTC, matteonu commented
Now the test should work.

2023-11-02 17:45 UTC, matteonu commented
> Now the test should work.
It seems like I forgot to set the sympy version back to 1.9 in the requirements.txt. I fixed it now.

2023-11-03 18:32 UTC, acalotoiu approved these changes
LGTM now! Thank you!

2023-11-03 20:26 UTC, merged