Fix for CUDA codegen
spcl/dace pull request #1442
Opened 2023-11-22 15:45 UTC by edopao

This PR addresses two errors detected during gt4py integration:
- `floordiv` runtime error: `floordiv` returns zero with `int` argument on baseline, it works by casting the argument to `double`.
- #1388 There is some old code change about rewriting the template functions for shared to global updates with WCR, which commented out the previous version. Reverting the template to its previous version solves this issue.

2023-11-30 15:44 UTC, tbennun requested changes

2023-11-30 15:44 UTC, tbennun commented on dace/codegen/targets/cuda.py
> +                        raise NotImplementedError(f'reduction not supported by template {funcname}')
Why is that the case? The C++ code allows it as far as I understand. Is it just a missing function?

2023-11-30 15:44 UTC, tbennun commented on dace/codegen/targets/cuda.py
> +                        ('    {func}<{type}, {bdims}, {copysize}, {is_async}>{accum}({args});').format(
We're missing a test for each of the two cases.

2023-11-30 15:44 UTC, tbennun commented on dace/codegen/targets/cuda.py
> +                             is_async='true' if state_dfg.out_degree(dst_node) > 0 else 'true',
`'true' if ... else 'true'`: was this the intent?

2023-11-30 15:44 UTC, tbennun commented on dace/runtime/include/dace/math.h
> +            return (int)std::floor(static_cast<double>(a));
that will slow down float code. I cannot approve that. Perhaps specialization for specific types is better here.

2023-11-30 16:02 UTC, edopao reviewed
Thank you the review, I will address your comments in a new commit.

2023-12-12 07:16 UTC, edopao commented
@tbennun Test added, please re-review.

2023-12-12 17:33 UTC, tbennun requested changes
Thank you. Only minor comments remain

2023-12-12 17:33 UTC, tbennun commented on dace/codegen/targets/cuda.py
> +                             is_async='true' if state_dfg.out_degree(dst_node) > 0 else 'false',
Same

2023-12-12 20:21 UTC, edopao commented on dace/codegen/targets/cuda.py
> +                        is_async='true' if state_dfg.out_degree(dst_node) > 0 else 'false',
Correct. I did not pay enough attention to `is_async` before. Besides correcting the value of this argument, I have also moved the synchronization point in the template function after the thread-level copy (see my last commit on copy.cuh).

2023-12-13 06:45 UTC, edopao commented
@tbennun Thank you for the review. As I commented above, I have done one additional change related to `is_async` flag.

2023-12-18 07:32 UTC, edopao commented
Gentle reminder for @tbennun: please check my last comment and whether you can approve this PR.

2023-12-18 15:13 UTC, tbennun approved these changes

2023-12-18 22:54 UTC, merged