Loop region codegen
spcl/dace pull request #1597
Opened 2024-06-13 16:02 UTC by phschaad

2024-06-27 14:15 UTC, tbennun requested changes

2024-06-28 09:13 UTC, phschaad commented on dace/codegen/control_flow.py
> +                expr += f'\n}} while({cond});\n'
yes, [`test_loop_do_for`](https://github.com/spcl/dace/blob/loop_region_codegen/tests/sdfg/loop_region_test.py#L89) tests for that.

2024-06-28 11:28 UTC, phschaad commented on dace/sdfg/analysis/schedule_tree/sdfg_to_tree.py
> +            result = [tn.StateLabel(state=node.first_block)] + result
Added [tests for that](https://github.com/spcl/dace/blob/loop_region_codegen/tests/sdfg/loop_region_test.py#L199) now :-)

2024-07-04 07:28 UTC, phschaad commented
@tbennun ping

2024-07-04 20:18 UTC, tbennun requested changes
Very very minor changes

2024-07-04 20:18 UTC, tbennun commented on dace/sdfg/analysis/schedule_tree/treenodes.py
> +                header = indent * INDENTATION + 'do:\n'
ha, nice. A good reminder that schedule trees are NOT Python :)

2024-07-04 20:18 UTC, tbennun commented on tests/sdfg/loop_region_test.py
> +def _make_tripple_nested_for_loop() -> SDFG:
```suggestion
def _make_triple_nested_for_loop() -> SDFG:
```

2024-07-04 20:18 UTC, tbennun commented on tests/sdfg/loop_region_test.py
> +    sdfg = _make_tripple_nested_for_loop()
```suggestion
    sdfg = _make_triple_nested_for_loop()
```

2024-07-04 20:18 UTC, tbennun commented on tests/sdfg/loop_region_test.py
> +    sdfg(A=a_test)
I think we want to test whether `generate_code()` has `do {` in it too.

2024-07-05 14:37 UTC, tbennun approved these changes

2024-07-05 16:48 UTC, merged