Add UUIDs to SDFG elements
spcl/dace pull request #1631
Opened 2024-08-26 10:48 UTC by phschaad

2024-08-26 14:22 UTC, tbennun commented
The diff looks good, the error is weird (because `super().__init__()` is called). I would refactor the uuid function to a central location so that it is configurable (e.g., for determinism).

2024-08-27 08:34 UTC, phschaad commented
I tried debugging the error a bit and I am genuinely super confused what is going on here. It doesn't even matter what I name the property, it really is like it is never defined for some instances of objects, but it is for others - despite `super().__init__()` seemingly being called everywhere, as you state.

2024-08-27 11:44 UTC, phschaad commented
It's `__deepcopy__`...

2024-08-27 18:03 UTC, tbennun commented
@phschaad so we already have a validation check that tests the uniqueness of `id(obj)` for objects for bad references. I wonder if we should also verify that for `obj.id` (probably secondary)

2024-08-28 13:06 UTC, tbennun requested changes

2024-08-28 13:06 UTC, tbennun commented on dace/sdfg/nodes.py
> +            if k in ('guid'):
Missing comma (elem,)

2024-08-28 14:15 UTC, tbennun approved these changes
LGTM, great addition!

2024-08-28 17:30 UTC, merged