Fix GPU transform mapping free access nodes always to GPU storage
spcl/dace pull request #1713
Opened 2024-10-30 09:20 UTC by ThrudPrimrose

Fix GPU transform mapping free access nodes always to GPU storage 
This results with tasklets running on host, that want to write to or read from data marked as GPU storage.

2024-10-30 09:30 UTC, ThrudPrimrose commented
Maybe I should add a pass that wraps any free tasklet with a default map of 1 iteration in a different PR?
I have a transformation that does that, I need to rewrite it to a pass and test it.

2024-11-27 16:53 UTC, mcopik requested changes

2024-11-28 11:06 UTC, ThrudPrimrose commented
I add test cases that catches the fixed bug. On the main branch:
```
FAILED tests/transformations/gpu_transform_test.py::test_free_tasklet_and_array[True] - dace.sdfg.validation.InvalidSDFGEdgeError: Data container "A" is stored as StorageType.GPU_Global but accessed on host (at state main, edge A[0] (assign:_out -> A:None))
```

On the bugfix branch:
```
9 passed, 7 warnings in 5.65s
```

2024-11-28 11:07 UTC, ThrudPrimrose commented on dace/transformation/interstate/gpu_transform_sdfg.py
> +        # Extend global_code_nodes with tasklets that write/read from an array
I add test cases that catches the fixed bug. On the main branch:
```
FAILED tests/transformations/gpu_transform_test.py::test_free_tasklet_and_array[True] - dace.sdfg.validation.InvalidSDFGEdgeError: Data container "A" is stored as StorageType.GPU_Global but accessed on host (at state main, edge A[0] (assign:_out -> A:None))
```

On the bugfix branch:
```
9 passed, 7 warnings in 5.65s
```

2024-11-29 07:45 UTC, phschaad approved these changes

2024-12-02 15:14 UTC, mcopik approved these changes

2024-12-03 00:21 UTC, merged