[Draft] Interstate assignment to map
spcl/dace pull request #1790
Opened 2024-11-21 16:15 UTC by ThrudPrimrose

Maps simple interstate assignments to map encompassing the whole state.
Will complete after the bug fix on re-declaration of symbols is merge.

2024-12-03 10:59 UTC, ThrudPrimrose commented
I should move this to a transformation. If the assigned symbol's value is used in more than one state, we need to wrap the whole subgraph where this value is necessary in a map and not just one state.

2024-12-17 02:21 UTC, tbennun requested changes

2024-12-17 02:21 UTC, tbennun commented on dace/transformation/passes/interstate_assignment_to_map.py
> +                condition = in_edge.data._cond_sympy
don't use the internal cached versions, use the methods that we provide.

2024-12-17 02:21 UTC, tbennun commented on tests/interstate_assignment_to_map_test.py
> +from typing import Dict
Missing copyright

2024-12-17 02:21 UTC, tbennun commented on tests/interstate_assignment_to_map_test.py
> +    test_interstate_assignment()
Please run yapf :)

2026-04-30 16:07 UTC, closed without merging