[Multi SDFG, Fortran] Prune redundant uses, which in turn allows pruning redundant objects more aggressively.
spcl/dace pull request #1840
Opened 2024-12-31 13:17 UTC by pratyai

2024-12-31 15:42 UTC, acalotoiu requested changes
Please add a test to check the functionality. LGTM otherwise

2024-12-31 17:26 UTC, pratyai commented
> Please add a test to check the functionality. LGTM otherwise

Thanks for pointing out. Turns out there was indeed a missing case.

2024-12-31 18:06 UTC, acalotoiu approved these changes
Nice! Thank you!

2024-12-31 18:07 UTC, acalotoiu commented
Have you also checked how it works when applied to ECRAD? (just as a side-note)

2025-01-01 00:07 UTC, pratyai commented
> Have you also checked how it works when applied to ECRAD? (just as a side-note)

Yeah, now it fails at a different place than `GET_COMMAND`; I guess that's a progress.

2025-01-01 07:19 UTC, merged