Adds 'TrivialMapElimination' and 'TrivialMapRangeElimination'.
spcl/dace pull request #374
Opened 2020-09-25 10:25 UTC by PanicSheep

2020-09-25 13:18 UTC, PanicSheep commented
Discussed with @am-ivanov to add tests to the transformations before merging.

2020-09-25 23:01 UTC, tbennun requested changes
small but fundamental change is necessary

2020-10-03 08:52 UTC, tbennun commented
@PanicSheep I would approve this PR if there was a test for it

2020-10-29 14:59 UTC, PanicSheep commented on dace/transformation/dataflow/trivial_map_elimination.py
> +        graph.replace(map_idx, map_from)
See commit "Only replaces map parameter on subgraph."

2020-10-29 14:59 UTC, PanicSheep commented on dace/transformation/dataflow/trivial_map_range_elimination.py
> +            graph.replace(map_idx, map_from)
See commit "Only replaces map parameter on subgraph."

2020-10-29 14:59 UTC, PanicSheep commented on dace/transformation/dataflow/trivial_map_elimination.py
> +        graph.replace(map_idx, map_from)
See commit "Only replaces map parameter on subgraph."

2020-10-31 22:48 UTC, tbennun requested changes
Almost done, rename a file and fix a range and it's approved!

2020-10-31 22:48 UTC, tbennun commented on tests/trivial_map_elimination.py
> +# Copyright 2019-2020 ETH Zurich and the DaCe authors. All rights reserved.
please add a `_test` suffix to the file so that it gets run automatically in CI. (we check for `tests/*_test.py`)

2020-10-31 22:48 UTC, tbennun commented on tests/trivial_map_range_elimination_test.py
> +    map_entry, map_exit = state.add_map('map', dict(i='0:1',j='0:5', k='j:j+1'))
This is an illegal map. the values of `k` cannot depend on `j`

2020-10-31 22:48 UTC, tbennun commented on tests/trivial_map_range_elimination_test.py
> +    map_entry, map_exit = state.add_map('map', dict(i='0:1',j='0:5', k='j:j+1'))
weird that it passes validation...

2020-11-02 12:33 UTC, tbennun approved these changes

2020-11-02 23:47 UTC, merged