User specified FPGA kernel boundaries
spcl/dace pull request #467
Opened 2020-11-10 15:59 UTC by TizianoDeMatteis

With this pull request, we want to allow the FPGA programmer to specify whether a given FPGA state must be code generated as an FPGA kernel or not.

To do this, we use the `location` property of the SDFG state. This has a key `is_FPGA_kernel`, that, by default is set to true. When is true, the state is inferred to be an FPGA Kernel.

Playing with this property, we can allow the generation of a separate FPGA kernel for each NestedSDFG

2020-11-16 23:02 UTC, definelicht requested changes

2020-11-16 23:02 UTC, definelicht commented on tests/fpga/nested_sdfg_as_kernel.py
> +                               memlet=dace.Memlet.simple(x.data, "i"))
`Memlet.simple` is deprecated, use `dace.Memlet(f"{x.data}[i]")`

2020-11-17 08:12 UTC, TizianoDeMatteis commented on dace/sdfg/state.py
> +        self.location["is_FPGA_kernel"] = True
Do you mean, not setting that default value and, whenever needed, check the value of that property if it exists?

2020-11-17 08:12 UTC, TizianoDeMatteis commented on tests/fpga/nested_sdfg_as_kernel.py
> +def make_vecAdd_sdfg(dtype=dace.float32):
are they listed somewhere? :)

2020-11-17 08:18 UTC, definelicht commented on dace/sdfg/state.py
> +        self.location["is_FPGA_kernel"] = True
Yes, location is a bit of a wild west in that sense

2020-11-17 08:18 UTC, definelicht commented on tests/fpga/nested_sdfg_as_kernel.py
> +def make_vecAdd_sdfg(dtype=dace.float32):
I believe we are following google conventions with exceptions

2020-11-17 08:20 UTC, definelicht commented on tests/fpga/nested_sdfg_as_kernel.py
> +def make_vecAdd_sdfg(dtype=dace.float32):
Also, mixing_underscores_and_camelCase is extra naughty 🤠

2020-11-17 15:06 UTC, definelicht requested changes

2020-11-17 15:06 UTC, definelicht commented on tests/fpga/multiple_kernels_stream.py
> +        memlet=Memlet.simple(in_host_a, "0")
`Memlet.simple` is deprecated :-) use `Memlet(f"{in_host_a}[0]")`

2020-11-17 15:06 UTC, definelicht commented on tests/fpga/multiple_kernels_stream.py
> +        memlet=dace.Memlet.simple(b_stream_out, '0', num_accesses=-1)
`num_accesses` is deprecated, use `dynamic=True`

2020-11-17 15:06 UTC, definelicht commented on tests/fpga/multiple_kernels_stream.py
> +    sdfg.save('/tmp/out.sdfg')
Remove I think?

2020-11-18 09:49 UTC, definelicht approved these changes

2020-11-18 10:11 UTC, merged