Removes annotate transformations for loops and branches
spcl/dace pull request #472
Opened 2020-11-11 13:19 UTC by phschaad

2020-11-11 23:17 UTC, tbennun requested changes
Please refactor and correct DF as discussed.

2020-11-12 10:26 UTC, tbennun requested changes

2020-11-12 10:26 UTC, tbennun commented on dace/sdfg/propagation.py
> +            # destination to it's source. We temporarily remove this.
```suggestion
            # destination to its source. We temporarily remove this.
```

2020-11-12 10:26 UTC, tbennun commented on dace/sdfg/propagation.py
> +                        # branch's dominance frontier. If a state has no
```suggestion
                        # branch's immediate post-dominator. If a state has no
```

2020-11-12 10:26 UTC, tbennun commented on dace/sdfg/propagation.py
> +                        # If the whole branch isn't dynamic anyway, and the
```suggestion
                        # If the whole branch is not dynamic,, and the
```

2020-11-12 10:26 UTC, tbennun commented on dace/sdfg/propagation.py
> +                        # branch's dominance frontier. If a state has no
Is it?

2020-11-12 12:12 UTC, phschaad commented on dace/sdfg/propagation.py
> +                        # If the whole branch isn't dynamic anyway, and the
fixed in 32ff4a7

2020-11-12 12:12 UTC, phschaad commented on dace/sdfg/propagation.py
> +                        # branch's dominance frontier. If a state has no
no, fixed in 32ff4a7

2020-11-12 12:12 UTC, phschaad commented on dace/sdfg/propagation.py
> +            # destination to it's source. We temporarily remove this.
fixed in 32ff4a7

2020-11-12 12:12 UTC, phschaad commented on dace/sdfg/propagation.py
> +                        condition=lambda _, child: child != guard))
adopted in 32ff4a7

2020-11-12 12:12 UTC, phschaad commented on dace/sdfg/propagation.py
> +                    v.ranges[itervar] = subsets.Range([rng])
adopted in 32ff4a7

2020-11-12 12:13 UTC, phschaad commented on dace/sdfg/propagation.py
> +                # No range detected, mark as unbounded.
fixed in 32ff4a7

2020-11-12 13:30 UTC, tbennun approved these changes

2020-11-12 14:08 UTC, merged