FPGA Transformations
spcl/dace pull request #515
Opened 2020-12-04 00:17 UTC by tbennun

- [x] StreamingMemory

2020-12-05 15:53 UTC, definelicht approved these changes
Nice tests!

2020-12-06 09:21 UTC, tbennun commented on dace/codegen/targets/xilinx.py
> +        for is_output, pname, p, interface_id in itertools.chain(arrays, scalars):
@definelicht note that I changed `parameters` to `arrays` here. It was probably wrong in the original code, since `arrays` was unused

2020-12-06 16:13 UTC, definelicht requested changes

2020-12-06 16:30 UTC, tbennun commented on dace/codegen/targets/xilinx.py
> +                var_name += "_if%d" % interface_id
Fixed

2020-12-06 20:10 UTC, definelicht approved these changes

2020-12-06 20:10 UTC, merged

2020-12-07 08:49 UTC, TizianoDeMatteis commented on dace/codegen/targets/intel_fpga.py
> +        # Ignore interface ID in this backend
There is no standard way of specifying interface in kernel arguments for Intel.
Unless you are referring to some ad-hoc solution to "automatically" interleave a buffer across multiple memory banks

2020-12-07 09:04 UTC, definelicht commented on dace/codegen/targets/intel_fpga.py
> +        # Ignore interface ID in this backend
No, I meant passing different pointers every time the same memory location is accessed, so the compiler has no idea about dependencies between them :-)