Rewrite control flow detection in code generator
spcl/dace pull request #520
Opened 2020-12-07 19:14 UTC by tbennun

- [x] Structured control flow code generator classes
- [x] Required modifications in framecode.py
- [x] "No control-flow detection" case
- [ ] Create structured control-flow tree from SDFG

2021-01-02 18:33 UTC, definelicht requested changes
Awesome to finally get a proper control flow analysis. I'm primarily missing some more docs on the control flow classes, and a summary of why we needed this in the first place/what problem(s) it solves (to justify having _another_ auxiliary graph representation).

2021-01-04 18:31 UTC, tbennun commented on dace/codegen/control_flow.py
> +    """ Simple switch-case scope wihout fallbacks. """
yep, was probably tired :)

2021-01-04 18:35 UTC, tbennun commented on dace/codegen/control_flow.py
> +        expr += 'goto __state_exit_{};\n'.format(self.sdfg.sdfg_id)
Will be documented. The answer: At the end of an if/else-if chain (which includes multiple outgoing edges with conditions), we cannot guarantee that all cases have been covered. If no outgoing edge matches, according to the SDFG semantics we must finish execution, hence the `goto exit`.

2021-01-05 10:43 UTC, definelicht approved these changes

2021-01-05 11:40 UTC, merged