Fix type inference for GPU scalars
spcl/dace pull request #579
Opened 2021-02-17 17:27 UTC by orausch

2021-02-18 12:19 UTC, orausch commented
This fix seems to work, but I'm not very confident that it covers all cases, especially since there are still many similar statements in the CPU codegen:
```
$ git grep 'isinstance.*pointer'
dace/codegen/targets/cpp.py:    is_scalar = not isinstance(conntype, dtypes.pointer) and desc.storage is not dtypes.StorageType.GPU_Global
dace/codegen/targets/cpu.py:        if isinstance(dtype, dtypes.pointer):
dace/codegen/targets/cpu.py:                is_scalar = not isinstance(conntype, dtypes.pointer)
dace/codegen/targets/cpu.py:        is_scalar = not isinstance(conntype, dtypes.pointer)
dace/codegen/targets/cpu.py:        is_pointer = isinstance(conntype, dtypes.pointer)
dace/codegen/targets/cpu.py:            if isinstance(cdtype, dtypes.pointer):
dace/codegen/targets/cpu.py:        elif isinstance(cdtype, dtypes.pointer):
dace/codegen/targets/cuda.py:                        if isinstance(field_type, dtypes.pointer):
```

2021-02-22 09:54 UTC, tbennun requested changes

2021-02-22 09:54 UTC, tbennun commented on tests/library/addlib/__init__.py
> +# Copyright 2019-2020 ETH Zurich and the DaCe authors. All rights reserved.
```suggestion
# Copyright 2019-2021 ETH Zurich and the DaCe authors. All rights reserved.
```

2021-02-22 09:54 UTC, tbennun commented on tests/library/scalars_gpu_test.py
> +import pytest
```suggestion
# Copyright 2019-2021 ETH Zurich and the DaCe authors. All rights reserved.
import pytest
```

2021-02-22 10:05 UTC, tbennun commented on tests/library/scalars_gpu_test.py
> +    assert output_arr[0] == 2
Missing `__main__`

2021-02-22 13:41 UTC, tbennun approved these changes

2021-02-22 15:21 UTC, merged