Stop redundant_array from creating non-Scope lifetime views
spcl/dace pull request #592
Opened 2021-02-22 23:03 UTC by orausch

2021-02-23 08:01 UTC, tbennun requested changes

2021-02-23 08:01 UTC, tbennun commented on tests/library/gemm_test.py
> +    Gemm.default_implementation = implementation
please keep the old implementation and set it back. pytest does not create new python scripts when running.
Also, not everyone has MKL so you need to either mark it as such or have a try/except block

2021-02-23 10:12 UTC, tbennun approved these changes
LGTM if passes

2021-02-23 16:30 UTC, orausch commented
Waiting on #590

2021-02-24 16:58 UTC, closed without merging

2021-02-24 16:58 UTC, orausch commented
merged in #597