Explicit control over Nested SDFG codegen
spcl/dace pull request #699
Opened 2021-05-03 13:49 UTC by TizianoDeMatteis

To allow more control over Nester SDFG code generation, the user can now:
- use a "hash" based approach (implicit): nested SDFGs with the same hash are code generated only once
- or, use the "unique_name" of SDFG (explicit): SDFGs with the same unique_name are generated only once
- or "none" of the above: a separate function is produced for each Nested SDFG 

This is controlled by a property in `dace.conf`.
Solves #697

2021-05-03 14:03 UTC, tbennun requested changes

2021-05-03 14:03 UTC, tbennun commented on dace/config_schema.yml
> +                    Determine if and how to generate the code for equivalent nestedSDFGs:
```suggestion
                    Determine if and how to generate the code for equivalent NestedSDFGs:
```

2021-05-03 14:03 UTC, tbennun commented on dace/sdfg/sdfg.py
> +    unique_name = Property(dtype=str,
I thought this was a property of the NestedSDFG node?

2021-05-03 14:07 UTC, definelicht commented
To be honest this approach is a bit dubious to me -- what happens if two SDFGs have the same `unique_name`, but are different?

I was hoping for an approach where we can guarantee programmatically that two nested SDFG nodes have the same SDFG _reference_, and therefore are identical.

This is not a good API, but an example of how you could guarantee this:
```python
sdfg = dace.SDFG("top_level")
nested_sdfg = dace.SDFG("nested")
sdfg.register_nested_sdfg(nested_sdfg)
state = sdfg.add_state("foo")
nested_sdfg_node = state.add_nested_sdfg("nested")
```

2021-05-03 14:19 UTC, TizianoDeMatteis commented
If the `unique_name` is the same, but the SDFGs are different, it will result in undefined behavior. 
It's up to the programmer to deal properly with this if he wants more control over NSDFG code generation.

Regarding your proposed API @definelicht , what will happen with the graphical representation of the SDFG?
If in the SDFG I have a Nested SDFG which is "registered", it becomes a sort of placeholder (like Access Nodes)

2021-05-03 14:24 UTC, definelicht commented
> 
> 
> If the `unique_name` is the same, but the SDFGs are different, it will result in undefined behavior.
> It's up to the programmer to deal properly with this if he wants more control over NSDFG code generation.

This is what I'm worried about, apart from being dirty, it's also not a nice workflow and has potential for bugs. For example, if you load the SDFG from JSON, and the nested SDFGs exist as two separate entities in memory. Then, you apply a transformation to one of the nested SDFG. But if you are unlucky and the other is found first, the transformation has no effect. It would be much nicer if this was guaranteed to work by design, so you could never get two copies of the same SDFG.

> Regarding your proposed API @definelicht , what will happen with the graphical representation of the SDFG?
> If in the SDFG I have a Nested SDFG which is "registered", it becomes a sort of placeholder (like Access Nodes)

Nothing would happen with the graphical representation: There is a unique mapping from each nested SDFG node to which SDFG it represents, so it's easy to retrieve this and draw the same way as we do now.

2021-05-03 21:59 UTC, tbennun commented
@TizianoDeMatteis @definelicht 
Another much simpler option is to prepend the hash (in a way that is invisible to the user) to the unique_name.

2021-05-04 08:33 UTC, definelicht commented
> 
> 
> @TizianoDeMatteis @definelicht
> Another much simpler option is to prepend the hash (in a way that is invisible to the user) to the unique_name.

That doesn't address my primary concern, which is to expose an explicit way for the programmer to instantiate nested SDFGs

2021-05-07 08:56 UTC, tbennun approved these changes
very minor change but otherwise approved

2021-05-07 08:56 UTC, tbennun commented on dace/codegen/targets/cpu.py
> +                            f'Different Nested SDFGs have tha same unique name: {sdfg_label}'
```suggestion
                            f'Different Nested SDFGs have the same unique name: {sdfg_label}'
```

2021-05-07 10:48 UTC, merged