Arm SVE Vectorization
spcl/dace pull request #748
Opened 2021-06-12 12:03 UTC by sscholbe

This is the pull request for implementing the vectorization transform for the Arm SVE codegen.

2021-06-14 15:48 UTC, tbennun commented on dace/transformation/dataflow/sve/vectorization.py
> +        nodes_between = graph.all_nodes_between(entry_node, exit_node)
use `graph.scope_subgraph`

2021-06-28 12:58 UTC, sscholbe commented on dace/transformation/dataflow/sve/vector_inference.py
> +from samples.fpga.jacobi_fpga_systolic import T
Classic VSCode

2021-06-28 14:03 UTC, sscholbe commented on dace/transformation/dataflow/sve/vectorization.py
> +from tests.buffer_tiling_test import I
+1

2021-11-15 23:28 UTC, tbennun requested changes
Minor changes

2021-11-15 23:28 UTC, tbennun commented on dace/codegen/targets/sve/codegen.py
> +                src_node.label + wcr[wcr.find('@') + 1:] + ');')
strange choice of implementation. please document why you do that!

2021-11-15 23:28 UTC, tbennun commented on dace/codegen/targets/sve/unparse.py
> +                return
?

2021-11-29 10:25 UTC, closed without merging

2021-11-29 10:25 UTC, tbennun commented
see #883