Move loop into map. Second version
spcl/dace pull request #754
Opened 2021-06-16 14:23 UTC by PanicSheep

2021-06-24 08:41 UTC, tbennun requested changes

2021-11-03 12:55 UTC, tbennun commented on dace/transformation/interstate/move_loop_into_map.py
> +        old_out_memlets = { memlet.data.data : memlet.data.subset.ranges for memlet in body.in_edges(map_exit) }
(1) was addressed, (2) wasn't.

2022-05-27 14:34 UTC, alexnick83 commented on dace/transformation/interstate/move_loop_into_map.py
> +        old_out_memlets = { memlet.data.data : memlet.data.subset.ranges for memlet in body.in_edges(map_exit) }
This code is obsolete and was removed.

2022-05-27 14:34 UTC, alexnick83 commented on dace/transformation/interstate/move_loop_into_map.py
> +        is_map = [isinstance(node, nodes.MapEntry) for node in body.nodes()]
These conditions were amended.

2022-05-30 10:21 UTC, alexnick83 approved these changes
LGTM

2022-05-30 11:25 UTC, merged